version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6380:6380"
  mongo:
    container_name: "campsi-mono-mongodb"
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db/
volumes:
  mongodb-data:
